### ISSUE TITLE
Convert spaces to tabs when typing or pasting code

### ISSUE THREAD

**Issue by peq** [peq/WurstScript#148]

**Comment by Cokemonkey11** [comment]
Instead, support spaces as replacement for tabs?

Tabs are for criminals. Embrace the 21st century of technology!

**Comment by peq** [comment]
This ticket is just about automatically converting pasted code to the whitespace-style used in the current file. Wurst supports tabs or spaces (was changed in May f7c19d0c8a5ea91e9327d4327643c20c7469a25e).

**Comment by Cokemonkey11** [comment]
Good call. Turns out I just needed to fix-up my eclipse plugin update site.

**Comment by peq** [comment]
The Eclipse plugin is no longer supported.
