### ISSUE TITLE
outline of standardlib isn't working

### ISSUE THREAD

**Issue by Ruk33** [peq/WurstScript#326]
![outline](https://cloud.githubusercontent.com/assets/1719111/5632659/29020b58-95af-11e4-8c7a-df4b668f6c95.jpg)

**Comment by peq** [comment]
If you import the standardlib as a project into eclipse it should show the outline. 

It would be some work to add the advanced features to files which are not part of an Eclipse project, so I don't think that I will fix this.

**Comment by Ruk33** [comment]
i will try that and i will let you know, thanks :)

**Comment by Ruk33** [comment]
ok, that made it work.

1. import
2. existing projects into workspace
3. select root directory: wurst/pack/folder/wurstscript/lib
4. done

thanks for the reply!
