### ISSUE TITLE
Report: JMpq fails if file from listfile is not found

### ISSUE THREAD

**Issue by peq** [peq/WurstScript#327]
```
File Not Found 
de.peeeq.jmpq.HashTable.getBlockIndexOfFile(HashTable.java:84)
de.peeeq.jmpq.JMpqEditor.<init>(JMpqEditor.java:79)
de.peeeq.wurstio.mpq.Jmpq2BasedEditor.<init>(Jmpq2BasedEditor.java:28)
de.peeeq.wurstio.mpq.MpqEditorFactory.getEditor(MpqEditorFactory.java:10)
de.peeeq.wurstio.Main.main(Main.java:122)
```

**Comment by peq** [comment]
hope that fixes the problem, but need some feedback from reporter

**Comment by Frotty** [comment]
What about the other threleven issues pöq.?

**Comment by peq** [comment]
Most of them are just minor issues. There is nothing with high priority label and everything with normal priority is also marked as only an enhancement. There is only one other reproducible issue marked as "bug". 

You should just join IRC again and tell me what is important :D

**Comment by peq** [comment]
Fixed by JMpq-v3
