### ISSUE TITLE
Fetch binary tools with build script, hide them with .gitignore

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#329]
The following bloat the repository and will lead to a slow, agonizing death:
- WurstPack\bin\worldedit.exe
- WurstPack\wurstscript\wurscript_b.exe
- WurstPack\vexorianjasshelper\jasshelper.exe
- WurstPack\vexorianjasshelper\clijasshelper.exe
- WurstPack\vexorianjasshelper\pjass.exe
- WurstPack\vexorianjasshelper\pjass_old.exe
- WurstPack\bin\exehack.exe
- WurstPack\mpqedit\mpqeditor.exe
- WurstPack\wurstscript\MpqCL.exe
- WurstPack\wurstscript\wurstscript.exe
- WurstPack\grimext\PatchGenerator.exe
- WurstPack\grimext\FileExporter.exe
- WurstPack\grimext\FileImporter.exe
- WurstPack\grimext\TriggerMerger.exe
- WurstPack\winmpq\WinMPQ.exe
- WurstPack\grimext\ObjectMerger.exe
- WurstPack\grimext\ConstantMerger.exe
- WurstPack\grimext\grimex.dll
- WurstPack\grimext\TileSetter.exe
- WurstPack\grimext\PathMapper.exe
- WurstPack\tesh\funclist.db
- WurstPack\tesh\horus.dll
- WurstPack\tesh\tesh.dll

If they are generated by WurstScript (successful builds) gitignore them. If they are tools required by WurstScript (libraries) fetch them with some equivalent of `make config` (I suppose you use ant), and gitignore them.

**Comment by peq** [comment]
They are not generated and as far as I know there is no reliable source to fetch them from, so I would rather have them in the repository. I don't think they will slow down the repository over time, since these are rather static files which are not updated anymore.

But maybe WurstPack can be put into a different repository.

**Comment by Frotty** [comment]
Sadly most of these are c++ binaries which we only use since they're part of newgen and we are too lazy to natively implement all of those. 
Cool to see you trying put wurst, but unless you have proper source with makes for all those they will stay. 
I didn't have any problems with this "bloated" repo. 

Also this isn't uncommon.

**Comment by Cokemonkey11** [comment]
@peq there are many reliable sources, for example google code and dropbox are free.

@Frotty definitely not interested in rewriting the binaries

**Comment by Cokemonkey11** [comment]
https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by Cokemonkey11** [comment]
@peq returning to this a year later, I'm supposing that this won't get scheduled?

I think it could make sense to put the standard library, wurst compiler, and wurstpack in separate repos, and make a script that bundles stuff. I imagine that it would make it easier to handle wurstscript releases.

**Comment by peq** [comment]
Well, it's kind of happening. But slowly. 

- Frotty has started a new version of the standard library in a separate repo: https://github.com/Frotty/StdLib2
- The new editor based on vscode is in a separate repo: https://github.com/peq/wurst4vscode

Once the new editor based on vscode is stable enough, I can ditch the Eclipse plugin (or at least entangle it from the compiler). Without the need for the Eclipse build system it becomes easy to use proper dependency management with gradle. 

So check back next year for this issue :)

**Comment by Cokemonkey11** [comment]
@peq Is there a roadmap for what's needed to cut stl and eclipse plugin from wurst repo?

Seems like the sort of thing I might be able to contribute with but not sure if will just be disruptive.

**Comment by peq** [comment]
Cutting stl: unit tests need to be changed to use stdlib from different
repo.

Eclipse plugin: either deprecate it completely or change it to use the same
interfaces as vscode

**Comment by peq** [comment]
@Frotty Gradle build is now working (on branch https://github.com/peq/WurstScript/tree/towards-gradle)
What is missing is:

- [ ] building the jar
- [ ] generating the hotdoc pages for stdlib
- [ ] changing the jenkins config
- [ ] Cleaning up the wurst repository 
- [ ] Running autoformat on the sourcecode and get rid of tabs :D

**Comment by Frotty** [comment]
I pushed 2 commits to remove local jars and make all tests succeed. Will do further work throwing things away 💃

**Comment by peq** [comment]
Wow, very big commit. It's a bit hard to see what happened, could you the
commit up and use single commits for deleting whole subdirs?

Otherwise it's hard to tell what happened here.

**Comment by Frotty** [comment]
I agree it's probably cleaner, but I don't really want to revert now. I think the beauty of git is, that nothing is ever lost and if you are missing something, you can always get it back.
What the commit did:
- remove libs folder and only depend on online artifacts
- remove eclipse plugin folders
- remove MpqCL folder
- remove parseq folder
- remove wurst starter folder

The overview on the github page is a bit bad too. In a decent git interface you can just see that all files are from same folders.

**Comment by peq** [comment]
Seems to work
