### ISSUE TITLE
Wurst Manual "Standard Lib" navbar link leads to Jenkins login

### ISSUE THREAD

**Issue by blakehawkins** [peq/WurstScript#330]
If you navigate here:

http://peq.github.io/WurstScript/manual.html

And click the Standard Lib link in the navbar:

http://peeeq.de/hudson/job/Wurst/HotDoc_Standard_Library_Documentation/index.html

You get:

http://peeeq.de/hudson/login?from=%2Fhudson%2Fjob%2FWurst%2FHotDoc_Standard_Library_Documentation%2Findex.html

**Comment by peq** [comment]
Should be fixed, but the generated documentation is still not very helpful.
