### ISSUE TITLE
Changes to mapfile results in status and mpq errors

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#334]
If I change wurstscript files and save my map, the wurst is compiled correctly and test-map works as expected.

However, if changes are made to the map and then saved in the editor (for example, removing a placed unit or adding a tree), a number of errors occur:

![1](https://cloud.githubusercontent.com/assets/1418966/6269620/484bdd08-b84c-11e4-8071-226b3d9cb574.PNG)

If I save a second time, a different error occurs (this error repeats if saving a third, fourth... time):

![2](https://cloud.githubusercontent.com/assets/1418966/6269630/5950fade-b84c-11e4-8082-559e822a4b4e.PNG)

**Comment by peq** [comment]
Does it happen every time?

Maybe the problem is that you are not using a frozen throne map (*.w3m vs *.w3x). Can you please check, if that problem occurs with (*.w3x) maps?

**Comment by Cokemonkey11** [comment]
turns out that if you place a blood mage the map becomes .w3x

but if you remove the blood mage it revert to .w3m

today I learned

**Comment by peq** [comment]
So then we have #335 for this bug, right?
