### ISSUE TITLE
wurst fails very ungracefully when used with reign of chaos map files

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#335]
If you try to compile a map written in wurst, but the map file is w3m rather than w3x, it produces very obscure errors about missing mpq objects.

**Comment by Frotty** [comment]
Yes, it is mentioned in the manual.

**Comment by Cokemonkey11** [comment]
Indeed, it's also repeated that it's necessary in your tutorials.

Still a bug.

Cokemonkey11 opened this 1 minute ago

**Comment by peq** [comment]
I agree that it is a bug. If I remember correctly, there was something strange about it. There was a reason why we said that we just support w3x. I will have to look into it again.

**Comment by Cokemonkey11** [comment]
In the worst case, providing a useful error, for example 

> Wurst only supports frozen throne map files (.w3x)

would at least prevent issues like #334 :+1:
