### ISSUE TITLE
[Standard Lib] all init blocks are compiled regardless of imports

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#339]
If a package is added to the standard lib with an init block, it is compiled and used even if no wurst imports it.

**Comment by peq** [comment]
This should not happen. Is this when starting from Eclipse or from the editor?

**Comment by Cokemonkey11** [comment]
I'm not entirely sure this does happen, I had an issue that @Frotty explained. Perhaps there is just some miscommunication here?

Frotty, do you recall what we were discussing?

**Comment by Frotty** [comment]
is this still an issue?

**Comment by Cokemonkey11** [comment]
@Frotty I don't remember. Do you remember the issue that we discussed/you explained above?

If no one remembers might be worth just closing for now...

**Comment by Cokemonkey11** [comment]
I think this might actually be related to compiletime generated objects for unit indexer (which I don't use so didn't want) or Fx dummy. Don't know which. Without some tool, it's sort of hard to check the full dependency graph. I think actually @peq did this for me once already.
