### ISSUE TITLE
CokeMonkey has problems when running wurst

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#341]
https://gist.github.com/Cokemonkey11/e47e5a87f4dd82730c35

When trying Run As in eclipse plugin.

He added this package, might be an issue
http://peeeq.de/code.php?id=8896

**Comment by peq** [comment]
Not really sure what the root problem is, but at least the error message should now contain more details.

Please try it again, and if it still is not working describe precisely what the steps are to reproduce the problem.

**Comment by Cokemonkey11** [comment]
Parent eclipse output: https://gist.github.com/Cokemonkey11/33a24e137ceabd092e14

Child error message:
![usure](https://cloud.githubusercontent.com/assets/1418966/6427404/14111c60-bf77-11e4-988b-a9811a382417.PNG)

**Comment by Cokemonkey11** [comment]
I run ant "gen" from eclipse, on project EclipseWurstPlugin. there are no errors...

**Comment by Cokemonkey11** [comment]
I don't know what has changed - this morning this bug was still very prevalent on my build. It seems to be working now, though. Will update if the problem persists.

**Comment by peq** [comment]
please reopen if still relevant.
