### ISSUE TITLE
Jurst incorrectly flags unused variables when nulling objects

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#350]
As far as I can guess, variables still need to be nulled in Jurst, but Jurst gives a warning `"The assignment to local variable t is never used."`

**Comment by peq** [comment]
No, Jurst basically has the same semantics as Wurst. It is just a different frontend which tries to look like vjass.

**Comment by Cokemonkey11** [comment]
So nulling variables isn't necessary, thanks.
