### ISSUE TITLE
Jurst imports dont resolve native visibility

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#354]
If jurst scope `Units` contains a native declaration `native UnitAlive takes unit u returns boolean`, and jurst scope `Codezors` has `import Units`, followed by a usage of `UnitAlive`, its visibility will fail to resolve and be inaccessible. Together with #353 this is a serious problem.

**Comment by peq** [comment]
Does it work, when you make the native public? That might be a temporary fix.

**Comment by Cokemonkey11** [comment]
I never considered that, yes it works, thanks.
