### ISSUE TITLE
After importing sounds Wurst stops working

### ISSUE THREAD

**Issue by ENAleksey** [peq/WurstScript#355]
I imported sounds in my map, now error occurred when I trying to save it:
![screenshot_1](https://cloud.githubusercontent.com/assets/12061580/7267397/edacf00e-e8d3-11e4-939a-f69ecb7eeecc.jpg)

**Comment by peq** [comment]
Can you please upload the sound somewhere? Is it a wav or mp3 sound?

@Crigges : do you have time to look at this bug?

**Comment by ENAleksey** [comment]
It is a wav. file. It happens with any sounds, I tried to save map without Wurst and it worked.

**Comment by ENAleksey** [comment]
With .mp3 files it works without error.

**Comment by peq** [comment]
@ENAleksey  : Can you please upload the wav file (or even better: a complete map with a wav file) which does not work for you? We are having problems reproducing the error. Thank you.

**Comment by ENAleksey** [comment]
[Test map](https://mega.co.nz/#!ec1zXYRA!iqBTnPlN7v3WaljEMZMdm0d8CfLqFhAmv9bnHX5hXsA)

**Comment by ENAleksey** [comment]
After importing [this texture](https://mega.co.nz/#!7Bdk2A4I!PuMLbopQM-qBbqSVSeQKUzGyMWCvh3j6ArxRJlHiQx8), error occurred too:
![screenshot_1](https://cloud.githubusercontent.com/assets/12061580/7471951/88255cda-f346-11e4-93cd-38136be5af09.jpg)

**Comment by peq** [comment]
@Crigges is working on a new version of the MPQ library. Maybe this problem would be fixed by it as well.

Until this is done, you could try to import stuff with the import tool. (Just put all imports into a folder named `imports` as done in the HotN (https://github.com/Crigges/HotN/tree/master/HotN) project.

If this does not work either, I could temporarily add optional support for external mpq editors again, but this had a lot of other problems.

**Comment by ENAleksey** [comment]
I tried to use import tool, but without success. I need these files, so what should I do?

**Comment by Frotty** [comment]
Not use .wav files. Convert them to .mp3 - if you want 3d sound, use https://github.com/peq/WurstScript/blob/master/Wurstpack/wurstscript/lib/small%20helpers/Simulate3dSound.wurst

**Comment by ENAleksey** [comment]
What about textures? I tried to remove the alpha channel, use compressed textures, but it is not working. Helps only reducing size of the textures, but I need the original size.

**Comment by peq** [comment]
Fixed by JMpq-v3

**Comment by ENAleksey** [comment]
Thank you, but now I use .dds textures instead of .blp :) I'm making graphic modification for WC3 (transfer game render to Direct3D 9) And I'm added support of .dds files.
If you are interested, please click here (http://www.hiveworkshop.com/forums/lab-715/reverse-engineer-game-dll-268718/index2.html)
