### ISSUE TITLE
Jurst doesn't understand the vjass "optional" keyword

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#357]
In vjass, a common pattern for public libraries is something like this:

    library Units requires optional AI
    endlibrary

    // may or may not exist:
    library AI
    endlibrary

Jurst doesn't understand the optional keyword.

**Comment by peq** [comment]
The optional keyword only makes sense if there is conditional compilation (static if preprocessor) which Wurst/Jurst does not have.

**Comment by Cokemonkey11** [comment]
Okay.
