### ISSUE TITLE
Some questions/suggestions to Standard library

### ISSUE THREAD

**Issue by Dafling** [peq/WurstScript#359]
Hello, I've been using Wurst for some time and I quite like it for a number of reasons. Among them extension functions is one of my favorites. Here is my feedback.

1. Native function `GetSpellTargetLoc()`, is there its Wurst counterpart `getSpellTargetPos()` ?

2. Is there a mechanism to convert between locations and positions, like `pos(location loc)`, or `location.getPos()` or `location.pos()`?

3. I need to be able to use some BJ functions, for example `function rect.getRandomPos()` which returns a random location/position inside that rect (BJ `GetRandomLocInRect(rect r)`). Is this function available somewhere in the library, or do I have to declare it myself?

4. I wasn't able to find `real.sqrt()` or `int.sqrt()`

5. Do you have plans to implement `const` keyword (conciseness)?

**Comment by Frotty** [comment]
You should never use locations at all in your code. 
Locations leak even if you destroy them, therefore wurst doesn't offer much functionality for them. 
Instead you should use the vec2/3 math tuple classes. 
For something like cast target you should use either the premade packages (like OnCast.wurst) or nativelyvec2(GetSpellTargetX(), GetSpellTargetY())). 

Getting a random point inside a rest is pretty trivial and doesn't require locations. 

The constant keyword Already exists

**Comment by Cokemonkey11** [comment]
The only thing not addressed is `real.sqrt` - didn't look into it myself
