### ISSUE TITLE
StdLib: unit.getFacing() should document degrees or radians

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#360]
The word angle is ambiguous, and it seems like a valid question: Does the stdlib transform GetUnitFacing(u) into radians, or does it just perform the native?

The eclipse popup documentation should say that it's in degrees.

**Comment by Frotty** [comment]
Well, ``.getFacing`` is somewhat deprecated, ``.getFacingAngle`` should be used to obtain the angle tuple.
Since there is no deprecated-annotation in wurst it could just get removed. (But would probably break some scripts/maps)

**Comment by Cokemonkey11** [comment]
![orly](https://cloud.githubusercontent.com/assets/1418966/7441289/fded47c2-f0d8-11e4-83b7-96311bfaaee6.png)

For the record I think they shouldn't be mutually exclusive - I don't see why you need to remove one of them. They're useful in different contexts.

**Comment by Frotty** [comment]
Yes, but in general natives were supposed to be deprecated or only useable with a specific import, and only std-lib wrappers be used, to avoid useage of locations, Angle instead of degrees/radians, etc.
How are they useful in different contexts? The tuple will give you a nice wrapper that will finally optimize to the original real.
It should always be used to prevent unit confusion.

I don't think a deprecated annotation is a good idea, that's why I'm not openeing a ticket for it.

**Comment by Cokemonkey11** [comment]
> The tuple will give you a nice wrapper that will finally optimize to the original real.

Yes, you're right. The case I was thinking was that you might get a unit's facing angle (in degrees) so you can create a new unit with the same facing angle - no abstraction or extra verbosity is necessary.

Deprecation affects all languages except ones that promise backwards compatibility, which is something you probably don't want. See: http://stackoverflow.com/questions/1234582/purpose-of-trigraph-sequences-in-c

**Comment by Frotty** [comment]
Well, the ````createUnit```` functions take angles as arguments:
https://github.com/peq/WurstScript/blob/678ae589d203f58dfe80cea4937fcfaa46c1921d/Wurstpack/wurstscript/lib/handles/Unit.wurst#L193

**Comment by Cokemonkey11** [comment]
I'm using Jurst, so I have CreateUnit() - anyway, I agree with your reasoning about using Angle. This can be closed.

**Comment by Frotty** [comment]
Well, Wurst has CreateUnit() too (just as Just has the stdlib), but in theory it shouldn't be used by non-std-lib packages.
The Documentation has been updated, i hope it helps.
