### ISSUE TITLE
optional ignore "expression is useless" errors

### ISSUE THREAD

**Issue by AlexYukikaze** [peq/WurstScript#362]
Can you do option to disable this error?
```
class ListNode
	use LinkedListModule
	
	static function all() returns LinkedList<thistype>
		let result = new LinkedList<thistype>()
		let e = ListNode.first
		while e != null
			if e instanceof thistype 			// ERROR: This instanceof expression is useless
				result.add(e castTo thistype) 	// ERROR: This castTo expression is useless
		return result
		
class Child extends ListNode
class ChildOfChild extends Child
// LinkedList<Child> childs =  Child.all() // will return Child and ChildOfChild
// LinkedList<ChildOfChild > childs =  ChildOfChild .all() // will return only ChildOfChild
```
Now i'm just copy this function to all childs. This copy-paste making me cry T_T
```
class ListNode
	use LinkedListModule
	
	static function all() returns LinkedList<thistype>
		let result = new LinkedList<thistype>()
		let e = ListNode.first
		while e != null
			result.add(e)
		return result
		
class Child extends ListNode
	static function all() returns LinkedList<thistype>
		let result = new LinkedList<thistype>()
		let e = ListNode.first
		while e != null
			if e instanceof thistype
				result.add(e castTo thistype)
		return result

class ChildOfChild extends Child
	static function all() returns LinkedList<thistype>
		let result = new LinkedList<thistype>()
		let e = ListNode.first
		while e != null
			if e instanceof thistype
				result.add(e castTo thistype)
		return result
```
PS Sorry for my english T_T

**Comment by Crigges** [comment]
Iam not sure what you are trying to reach but your code fails for a reason.

The main issue is that thistype does not represent any of your subclasses in this context. It refers just to your class ListNode.

I would recommend you to use the LinkedListModule in each subclass and add a function all() to the module.

**Comment by Frotty** [comment]
Hi, 
My understanding of your code is, that you have a parent class that uses linkedListModule, and child classes. Now you want the static function all() to return all instances of the childclass. 
Your current version doesn't work, because thistype in a static method will always refer to the class it 's implemented in. 

Instead make use of .typeId.
http://peq.github.io/WurstScript/manual.html#typeid

**Comment by AlexYukikaze** [comment]
I understood thanks for the explaining.
btw ```instanceof thistype``` not work in module :(
