### ISSUE TITLE
Eclipse: Mark occurences

### ISSUE THREAD

**Issue by peq** [peq/WurstScript#370]
Mark occurrences of variables when cursor is on the variable.

**Comment by Frotty** [comment]
:+1:

**Comment by peq** [comment]
First version is working:

![Screenshot](http://i.imgur.com/ZZqfrZ7.png?1)

 Color and some other things can be changed in the Eclipse preferences under General->Editors->Text Editors->Annotations.

Some things are still required:
- do processing in a background task to not slow down the real editor
- add an option to enable/disable this feature (maybe even a toggle button as in eclipse)
- optimize some positions (sometimes too much of an element is highlighted)

**Comment by peq** [comment]
The eclipse plugin is no longer supported.
