### ISSUE TITLE
Ant targets metadata file is not ignored by git

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#382]
`de.peeeq.wurstscript/.ant-targets-build-jar.xml` should be `.gitignore`'d

**Comment by peq** [comment]
I don't have this file. Probably it is something specific to the tools you are using, so maybe add it to your global ignores.

It seems to come from some bash completion tool for ant.

**Comment by Cokemonkey11** [comment]
> It seems to come from some bash completion tool for ant.

Yes, this is being generated by ant's command line tool. Something like this:

`ant -buildfile build-jar.xml make<tab>` fills in `make_for_wurstpack`

I suggest adding it to the project gitignore file.

**Comment by peterzeller** [comment]
If it is specific to the tools you have installed on your pc it should be going in your global .gitignore, not the projects .gitignore.

**Comment by peq** [comment]
If it is specific to the tools you have installed on your pc it should be going in your global .gitignore, not the projects .gitignore.

**Comment by Cokemonkey11** [comment]
It is specific to `ant`, which is necessary for building the project. I can only assume that you don't have this generated file because you're using eclipse builds.
