### ISSUE TITLE
Eclipse plugin should allow automatic remove trailing whitespace

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#383]
The Eclipse Java and C++ formatters have features to allow the automatic removal of trailing whitespace on lines (and blank lines) during save. Can we add this to Wurst?

Alternatively, we should have a SublimeText wurst colorizer, because writing a trailing whitespace plugin shouldn't be the job of a language developer...

**Comment by peq** [comment]
I did not try it, but the [AnyEdit](http://andrei.gmxhome.de/anyedit/) plugin for Eclipse claims it can do this.

If you want to create a language definition for Sublime you can take the keywords from https://github.com/peq/WurstScript/blob/a2d2bd2a6e98a0dd3e9b2e30994f1c2b45c2f8f0/de.peeeq.wurstscript/src/de/peeeq/wurstscript/WurstKeywords.java

**Comment by Cokemonkey11** [comment]
I'm not really interested in either of those options - if you don't want to follow the behavior of the java and C++ formatters then just close this.

**Comment by Frotty** [comment]
I think a wurst formatter for the Eclipse plugin would be nice. But there aren't even quick fixes yet.

**Comment by peq** [comment]
A formatter is probably easier to do. But that would be a different ticket.
