### ISSUE TITLE
Introduce check for maximum instances in debug mode

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#384]
Please check if there can be a new instance allocated in the class-allocator and print an error if it's maxed.

**Comment by peq** [comment]
There is no "debug-mode". There are just options to disable some of the checks. So the question is whether we should make it default with an option to disable the checks or if we do it the other way?

**Comment by Cokemonkey11** [comment]
Initial configuration is arbitrary for such minutiae - just pick something and go with it.
