### ISSUE TITLE
Discuss: Compiletime replacements for functions

### ISSUE THREAD

**Issue by muzzel** [peq/WurstScript#385]
Idea: add an annotation that allows the user to define a replacement for a function, which is used when the function is executed in compiletime.

Example:
```
function bla()
    doSomething()

@compiletimereplacement function bla()
    doSomethingElse()
```
When ``bla()`` is executed during runtime, the normal ``doSomething()`` version is used. If ``bla()`` is executed in compiletime, the ``doSomethingElse()`` version is used.
If there is no ``@compiletimereplacement`` defined for a function, the normal version is used for both runtime and compiletime.

Someone should probably come up with a shorter name for the annotation :p

**Comment by peq** [comment]
Why not  something like this?

	function bla()
		if compiletime
			doSomething()
		else
			doSomethingElse()

I am planning to add something like `compiletime` as a built-in constant, see discussion in #365

**Comment by muzzel** [comment]
Yea that works too, just thought it might be comfortable.

But I didnt notice that it completely destroys readability (similar to vJass hooks), so its a bad idea anyway.
- Can be closed. -
