### ISSUE TITLE
Folding imports is still broken

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#387]
E.g.
![](http://i.imgur.com/m7zhobF.png)

This happened randomly after openeing/closing a few times and removing empty lines.
Another very annoying thing is that when you press Enter with the cursor at the end of the imports like this:
![](http://i.imgur.com/ks5v4bO.png)
You end up like this below the first import (a new blank line is created line 4):
![](http://i.imgur.com/Q3vAiyx.png)
But The cursor should be below the last import.

Also, if you leave the blank line wurst created above and try to fold again, this happens:
![](http://i.imgur.com/Kqh7KSB.png)

**Comment by Frotty** [comment]
Still happening and still very annoying..

**Comment by peq** [comment]
> Another very annoying thing is that when you press Enter [...] a new blank line is created

Eclipse with Java works the same way, so I would say this is expected behaviour. 

> E.g.
> ![](http://i.imgur.com/m7zhobF.png)
> 
> This happened randomly after openeing/closing a few times and removing empty lines.

I cannot reproduce this. Maybe this is still a problem with Windows newlines?

> Also, if you leave the blank line wurst created above and try to fold again, this happens:
> ![](http://i.imgur.com/Kqh7KSB.png)

Also not reproducible. Can you provide more precise steps? Does this happen every time?

**Comment by Frotty** [comment]
It breaks so easily for me... how can you not reproduce this? Maybe it's windows LR stuff
Anyways, I will provide you the exact steps:
1. Go to Collider.wurst in the StandardLib with folding imports enabled. Should look like this:
````
package Collider
import Fx

constant real DEFAULT_COLLISION_SIZE  	=   50.0
````
2. Place the cursor after `import Fx`, and press Enter, creating a newline inside the imports
3. Remove the empty line 7, separating the imports from constants
4. Fold the imports. **It is now broken and looks like this**:
````
package Collider
import Fx
import LinkedList
constant real DEFAULT_COLLISION_SIZE  	=   50.0
````

5. Add another newline after `import Fx` by pressing enter
6. Add a newline after after `import LinkedList` by pressing Enter at the end of it
7. Fold the imports - **the newline we added in the previous step is being folded, even though it should not**.
8. Place the cursor in front of the 9th line `constant real DEFAULT_COLLISION_SIZE` and press Enter, creating a newline between the imports and the constant
9. Add another newline after `import Fx` by pressing Enter at the end.
10. Remove the 3 empty lines between `import Fx` and `import TimedLoop`
11. Fold the imports. **You will be presented with something similar to the screenshot**
![](http://i.imgur.com/Kqh7KSB.png)

As mentioned before, this is just one way to make this happen. Sometimes blank lines are being eaten, and suddenly re-appear. The 2-dot boxes appear at wrong places and multiple times.

**Comment by peq** [comment]
Hmm, I did the exact same steps, but I get the expected behaviour, not your buggy behaviour. Maybe I will try this again, when I am on Windows. It might also be a problem with your Eclipse version.

**Comment by Frotty** [comment]
I can try a different eclipse version. I have used a fresh mars install on 2 different PCs, producing the exact same behaviour.

**Comment by Frotty** [comment]
And also reproduced on Crigges' PC.

**Comment by Frotty** [comment]
Okay I fixed a step in the description, and it is to note that **the lines have to be removed via backspace**, not ctrl+D

**Comment by peq** [comment]
Ok, with backspace I can reproduce at least the first part.

**Comment by Frotty** [comment]
Additionally to the backspace problem, the auto-reconciling also has some part in this.
When I reduce the concile-delay in options to 0.1ms, add a blank line and remove it (with any key, also ctrl+d) and then **quickly** fold the imports, the imports unfold on their own after a small delay.

**Comment by Crigges** [comment]
![No idea what frotty did](http://snag.gy/T7FLE.jpg)

**Comment by peq** [comment]
>  add a blank line between imports and remove it (with any key, also ctrl+d) and then quickly fold the imports

![](http://i.stack.imgur.com/U1mq6.jpg)

(Sorry, I had to think of this joke. Of course this is a problem and should be fixed.)

The folding depends on the reconcilation, because it gets the import-positions from the parser. So correct folding is only possible after reconcilation is finished. Something seems to get mixed up when you do something in between. 

The other problem is probably something about how Eclipse handels folding markers when the Text is changed.

**Comment by Frotty** [comment]
We need import folding for vscode but that can get a seperate ticket.

**Comment by peq** [comment]
I think vscode currently has no option for custom folding. So an alternative option would be to change the language to  allow shorter imports like 

```
import Entity Physics Spells
```
or intended comments like
```
import 
    Entity 
    Physics 
    Spells
```

**Comment by peq** [comment]
PS: vote on this issue: `https://github.com/Microsoft/vscode/issues/3422`
