### ISSUE TITLE
Ignore unused variable warning in lambda expression

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#388]
````
public abstract class OnExpireEvent
	abstract function onExpire(vec2 pos, player owner)

...
	(vec2 pos, player owner) -> ...
````
E.g. if owner isn't used in this closure, as it is not needed, it still has to be defined in the lambda but throws a warning.

**Comment by peq** [comment]
if you don't want to use a variable, just prefix the name with an underscore: 

    (vec2 pos, player _owner) -> ...

This is a feature stolen from Erlang (and I think I saw it somewhere else as well).

It still needs to be mentioned in the manual, though.
