### ISSUE TITLE
Allow subclasses to access members from super modules uses

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#390]
````
module M
	int i

class A
	use M
	
class B extends A
	
	function foo()
		this.i++
		super.i++
````

this.i throws
````
Could not resolve reference to variable i for receiver of type B.
````
super.i throws 
````
Cannot access dynamic variable i from context of type B.
````

**Comment by Crigges** [comment]
You can use them but since "first" and "last" are static you can't access them in non static context.
There is also the problem that you can use the same module in class B. So if you would use the members first and last would be ambiguous. So this is the way to go:
```
class A
	use LinkedListModule

class B extends A
	use LinkedListModule
	
	static function foo()
		A.first = A.first // <-- No Problem here
		first = first // <-- No problem here
```

**Comment by Frotty** [comment]
I fixed the example to showcase the actual error

**Comment by Crigges** [comment]
Rel

https://github.com/peq/WurstScript/issues/214

**Comment by peq** [comment]
Should be fixed with https://github.com/peq/WurstScript/commit/45154698d1ed0148e0529dea77d603b5f6ff34f6
