### ISSUE TITLE
[StandardLib] unit.issueImmediateOrder is missing

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#393]
There is a `unit.issueImmediateOrderById()`, but that's not what I'm looking for.

@Frotty

**Comment by Frotty** [comment]
unit.issueImmediateOrderById(OrderId("order"))

**Comment by Crigges** [comment]
You can create pull requests for stuff like this.
Just fork the repo :)

**Comment by Cokemonkey11** [comment]
@Frotty yeah I can equally use `IssueImmediateOrder(unit, "order")` - it's just a missing method

@Crigges I know ^^

**Comment by Frotty** [comment]
see 81db3d70fbbf1aaf5773ec0439f68b58d7271655
