### ISSUE TITLE
Eclipse "Extract to Files" feature fails silently if the w3x is in use

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#395]

**Comment by Frotty** [comment]
Can you elaborate on this? The map is always in use if it's opened with the editor - which you need in order to Extract all files.
Also the map is copied and the imports are extracted from that copy.
The only reason I could imagine would be missing rights in the temp folder or so..

**Comment by peq** [comment]
The eclipse plugin is no longer supported.
