### ISSUE TITLE
Jurst/Eclipse error "exprbinary depends on itself when evaluating attribute ConstantValue"

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#398]
I'm not sure what to make of this:

```
		constant integer    MAX_ROW_COUNT        = 100
		constant integer    MAX_COLUMN_COUNT     = 30
		constant integer    MAX_ARRAY_SIZE       = MAX_ROW_COUNT*MAX_COLUMN_COUNT
```

I also get "Array size is not constant expression" for the following:

```
struct myBoard
		private  integer        array charCnt [MAX_ARRAY_SIZE]
```

**Comment by peq** [comment]
Currently it has to be really a constant, not a constant variable. The problem is that the number has to be known at compiletime, so we cannot allow all kind of constants, but I agree that we could make it more flexible.

**Comment by Cokemonkey11** [comment]
Excellent, thank you!
