### ISSUE TITLE
Eclipse console can't do anything

### ISSUE THREAD

**Issue by Crigges** [peq/WurstScript#400]
Error: java.lang.RuntimeException: Modelmanager was locked for build

Already tryed:
Restart Eclipse
Reinstall Wurstplugin
New Empty Project
Clean Project
Pray to peq
Nothing seems to work :(

**Comment by Frotty** [comment]
This issue still persists when the executed code throws any kind of error

**Comment by peq** [comment]
Works for me after different kind of errors:

```
Welcome to Wurst, the best language since sliced bread!
Type 'help' to get help.
> 1/0
cannot store result of computation: Infinity
> 1+1
res = 2     // integer
> error("hey")
Error: hey... when calling repl_start()
... when calling error("hey")
... when calling error("hey")

> 1+1
res = 2     // integer
> S2I("1")
Error in last entered statement:
function S2I not found
> 1+1
res = 2     // integer
> 
```

**Comment by Frotty** [comment]
````
string s = "test" 
s.charAt(10)
````
Untested, but something like this where a Java method is used that can throw (uncaught ?) exceptions
