### ISSUE TITLE
New all in one Wurstscript.rar

### ISSUE THREAD

**Issue by Crigges** [peq/WurstScript#402]
The old version was a outdated and buggy.
New version features:
-Better minimal eclipse, with proper icons and less size
-Upgraded from eclipse Luna to Eclipse Mars
-New optional batchfiles to start Wurstpack and eclipse as administrator
-Decreased compressed size by 15MB from 156MB to 141MB
-Deleted sample project and workspace since the wurst.dependenices file does not support relative pathes
-Added missing checksums.md5 file to the Wurstpack which could result in unwanted behavior

I just need someone who can host the .rar

**Comment by Cokemonkey11** [comment]
@Crigges have you considered speaking with Ralle about hosting it on THW?

**Comment by peq** [comment]
Does this include your new launcher exe?

**Comment by Crigges** [comment]
@Cokemonkey11 Wurstscript shouldn't be hosted on THW it should be independend in my opinion.

@peq No this would be pointless since the archive contains a minimized portable jre8 which is always used by the Wurstpack and eclipse.
But I could create some pack without java and the new java launcher.

**Comment by Crigges** [comment]
So want to host this or not?

**Comment by peq** [comment]
I can host it, just send it to me somehow.

**Comment by Crigges** [comment]
If i could send it it you won't need to host it :D

**Comment by peq** [comment]
If you cannot send it to me or to my server, how can I host it?

**Comment by Crigges** [comment]
We managed to host the file: http://peeeq.de/wurst/Wurstscript_2015_09.zip
