### ISSUE TITLE
Compiling wurst fails | Update Readme

### ISSUE THREAD

**Issue by Crigges** [peq/WurstScript#406]
Iam trying to get the wurstscript project runing in eclipse. I followed the introductions inside the readme (running the antbuild), I also tryed to build the project using the Maven in eclipse but without success.
So how to import the project and compile it?

**Comment by peq** [comment]
So what is the error message?

**Comment by Crigges** [comment]
http://snag.gy/42u39.jpg

**Comment by peq** [comment]
Looks like you imported it as a maven project, instead of importing the existing Eclipse project.
Also something seems wrong with your Java build path, check what the error is in the project properties.
