### ISSUE TITLE
Improve HotDoc Window

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#412]
Mainly:
- Make it remember the size like the autocomplete window
- Display information more precise
  - Better overview of the parameters
  - Avoid unnecessary linebreaks
- Maybe add some configuration
- Ideally add hyperlinks to displayed information so you can ctrl+jump to them

**Comment by peq** [comment]
Maybe you can describe a bit more precisely what you mean here:

> HotDoc Window

You mean the window that appears when you hover over a function with the mouse?

> Better overview of the parameters

All parameters are shown, so what would be better? One parameter per line?

> Avoid unnecessary linebreaks

Which ones?

> Maybe add some configuration

What should be configurable?

> Ideally add hyperlinks to displayed information so you can ctrl+jump to them

You mean allowing links in Hotdoc?

**Comment by Frotty** [comment]
> You mean the window that appears when you hover over a function with the mouse?
The yellow-ish window I did, yes, and it also shows up next to the autocomplete
> All parameters are shown, so what would be better? One parameter per line?
I'm not 100% sure yet, but currently the font is too big which makes the parameters wrap multiple times, and in awkward spots too, for example splitting the parameter type from the name.
> Which ones?
By this is ment the avoidance of bad wrapping and probably removing space when there is no hotdoc
> What should be configurable?
e.g. Font, fontsize, colors, what to display exactly
> You mean allowing links in Hotdoc?
Yes. For non-primitive parameters, the function itself and the package it is declared in

**Comment by Frotty** [comment]
Additionally it should be detected when a native/bj is used.

**Comment by peq** [comment]
> Additionally it should be detected when a native/bj is used.

And what should happen then? If I just detect it and do nothing then what's the point?

**Comment by Frotty** [comment]
Instead of "no hotdoc provided" display "blizzard native" or something.
An advanced feature would be to try and retrieve the blizzard comments.

**Comment by peq** [comment]
There are hardly any comments in the Blizzard files.

**Comment by peq** [comment]
Could try to extract comments from mappedia, although that would only be in German.

**Comment by Frotty** [comment]
We could try adding hotdoc to the natives, but who wants to do that :no_good: 
There are not many comments, but some useful ones, also related to events (which event uses which getters, etc.)
This is just an idea, of course. :chicken:

**Comment by peq** [comment]
The Eclipse plugin is no longer supported.
