### ISSUE TITLE
Wursteclipse does not always auto-indent

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#417]
When creating a newline by pressing enter at the end of a line, sometimes wurst automatically increases the indentation-level by one tab, as it should.
This works for ifs, while/for-loops, etc. - but not for:
- non-abstract functions headers
- switches, cases

Yet not indenting isn't allowed for these structures.
Does this have any specific reasoning?

**Comment by peq** [comment]
If you want to change something, you could try to start here: https://github.com/peq/WurstScript/blob/master/EclipseWurstPlugin/src/de/peeeq/eclipsewurstplugin/editor/autoedit/WurstAutoIndentStrategy.java#L18

Or you wait until I find time for this :P

**Comment by Frotty** [comment]
:+1:
