### ISSUE TITLE
Launching map gets stuck at 24% "Launching delegate..." and Eclipse uses 650+ MB RAM

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#421]
![image](https://cloud.githubusercontent.com/assets/1418966/10954852/c9b5f786-8347-11e5-851e-c3547e771817.png)

It happens to be a new map that has not yet been successfully run by wurst.

I launch it by right clicking the w3x file in eclipse and selecting "run as Wurst".

**Comment by Crigges** [comment]
My eclipse uses 2GB Ram if it is hungry so be be happy with 700MB

The launch seems to be stucked in a infinity loop. Better show us the console output instead of the progressbar.

**Comment by Cokemonkey11** [comment]
I cleaned and rebuilt wurst, and deleted the `wurst/war3map.j` file and rebuilt by saving the map in wurstpack, then tried doing again "run as > wurst":

![image](https://cloud.githubusercontent.com/assets/1418966/10983071/7f43fef2-8408-11e5-91e4-e7f564197936.png)

Wurst console only shows:

```
building project rise-of-daolmir, please wait ...
```

**Comment by Crigges** [comment]
Looks like you are using a old wurstscript version.

**Comment by Cokemonkey11** [comment]
@Crigges nope, it's the newest clean build from peq/Wurstscript/master

**Comment by Crigges** [comment]
Start eclipse via the eclipsec.exe and show us the cmd output.

**Comment by Cokemonkey11** [comment]
When I right click map and select "run as > wurst" I get different errors sometimes, it seems. In this particular example:

![image](https://cloud.githubusercontent.com/assets/1418966/11020893/215be3b0-8627-11e5-9f79-7dc6ac50c002.png)

And here is the output of eclipsec.exe -

https://gist.github.com/Cokemonkey11/8b9494bd99540559bc4d

**Comment by Crigges** [comment]
JMpq-v2 is used instead of v3. This was fixed a few commits ago. Check the stacktrace on your own:
The stacktrace points to:
  at de.peeeq.eclipsewurstplugin.console.WurstREPL.compileScript(WurstREPL.java:641)

This is the line:
https://github.com/peq/WurstScript/blob/master/EclipseWurstPlugin/src/de/peeeq/eclipsewurstplugin/console/WurstREPL.java#L641

So since line 641 is ```}``` your eclipse plugin version is outdated.

**Comment by Cokemonkey11** [comment]
Crigges, thanks a lot for the help so far.

Yes, I did find it strange that there weren't any automatic updates in a while.

![image](https://cloud.githubusercontent.com/assets/1418966/11046129/72159d4e-8723-11e5-99e5-f79159072eec.png)

![image](https://cloud.githubusercontent.com/assets/1418966/11046134/787b98f0-8723-11e5-9295-9d4b91ac15dd.png)

And here's my full error log (have never opened this view, afaik):

![image](https://cloud.githubusercontent.com/assets/1418966/11046183/ce3f110e-8723-11e5-8937-558fda7b73db.png)

**Comment by Crigges** [comment]
Ye i know this problem. It was an issue with one special wurstbuild. Just uninstal the Wurstscript plugin via: Help -> About Eclipse -> Installation Details and reinstall it again.

**Comment by Cokemonkey11** [comment]
I've just done that, and tried to run it again. Running the map as Wurst fails, and here is the error log:

![image](https://cloud.githubusercontent.com/assets/1418966/11071091/eb9520b4-87d6-11e5-94ff-7e9c1e802352.png)

**Comment by Cokemonkey11** [comment]
@Crigges I think you mentioned that you figured out the problem with this and it should be patched?

**Comment by Crigges** [comment]
Those "Could not extract xyz errors" should only occur if the file is missing inside the .mpq.
Check the following:
-Does the map contain those files?
-Try a differernt map, maybe jmpq2 broke something
-If this is a jmpq bug i need some way to reproduce it. Can you offer me your code and and map?
