### ISSUE TITLE
stdlib base64

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#445]
I think base64 encoder/decoder would be a healthy addition to the standard library. I saw already that Frotty has done some crypto here - https://github.com/Frotty/EBR/blob/876789f7f6087ce32c09d4603468749ef0b02fe7/wurst/player/CodeGenerator.wurst

How do you guys feel about this? I've never bothered doing this sort of stuff in wc3, but I have a use case that might warrant writing it.

**Comment by Frotty** [comment]
base64 != crypto, but sure go ahead.
