### ISSUE TITLE
Wrong warning for public imports

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#449]
Just like #381 this produces a warning one cannot get rid of.

````
package T1

public class A

package T2
import public T1

package T3
import T2 <-- The import T2 is never used directly

class B extends A
````
When removed this of course causes a compilation error.

**Comment by peq** [comment]
Well, you can get rid of it by importing T1 instead of T2. Why do you want to import T2, if you are not using anything from T2 directly?

**Comment by Frotty** [comment]
because I have many public imports in T1 and many in T2 that are used in many other package where I want to keep the import list small by moving them into public imports.

**Comment by Frotty** [comment]
fixed and now a warning shows you excessive imports - nice.
