### ISSUE TITLE
compile logic error?

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#450]
Hi,

I have some quite straightforward boolean logic. It's possible that I'm just tired/stupid, but I think this looks like a bug in jurst/wurst.

Here is code:

		static function checkSkip()
			BJDebugMsg("checkSkip " + I2S(Units.runnerTypes[0]) + " " + I2S(Units.runnerTypes[1]) + " " + I2S(Players.playingCount) + ".")
			if (Players.playingCount == 1) or (Units.runnerTypes[0] != 0 and Units.runnerTypes[1] != 0) then
				BJDebugMsg("checkSkip success")
				DestroyTimer(Game.chooseTimer)
				DestroyTimerDialog(Game.chooseDialog)
				TimerStart(CreateTimer(), 15., false, function Game.practiceRound)
			end
			BJDebugMsg("checkSkip done")
		end

and here is output:

![image](https://cloud.githubusercontent.com/assets/1418966/16540720/45df7ec8-4066-11e6-95fe-4b07b071999f.png)

**Comment by Cokemonkey11** [comment]
Looks like it is indeed a false translation. Here's from war3map.j:

	function Game_checkSkip takes nothing returns nothing
		call BJDebugMsg("checkSkip " + I2S(Units_runnerTypes[0]) + " " + I2S(Units_runnerTypes[1]) + " " + I2S(Players_playingCount) + ".")
		if Players_playingCount == 1 or Units_runnerTypes[0] != 0 and Units_runnerTypes[1] != 0 then
			call BJDebugMsg("checkSkip success")
			call DestroyTimer(Game_chooseTimer)
			call DestroyTimerDialog(Game_chooseDialog)
			call TimerStart(CreateTimer(), 15., false, ref_function_Game_practiceRound)
		endif
		call BJDebugMsg("checkSkip done")
	endfunction

**Comment by Cokemonkey11** [comment]
[15:15] <Cokemonkey11> just added a comment
[15:19] <lep> probably this https://github.com/peq/WurstScript/blob/master/de.peeeq.wurstscript/src/de/peeeq/wurstscript/jassprinter/JassPrinter.java#L267-L268
[15:20] <lep> while and and or in jass seem to have the same prec
[15:21] <Cokemonkey11> is it an easy fix?
[15:21] <Cokemonkey11> I don't know much about the internals of the wurst compiler
[15:21] <lep> me neither
[15:21] <lep> but should be very easy
[15:25] <lep> https://github.com/peq/WurstScript/blob/master/de.peeeq.wurstscript/src/de/peeeq/wurstscript/jassprinter/ExprPrinter.java#L69-L71

**Comment by peq** [comment]
Really? So what is correct? Both have the same precedence?


This is probably broken in the Jass parser as well. However, I am not sure if this should be fixed in the parser, as this might break some code.

**Comment by Cokemonkey11** [comment]
In JASS, it seems they both have the same precedence, yes.

> This is probably broken in the Jass parser as well. However, I am not sure if this should be fixed in the parser, as this might break some code.

I'm not sure what you mean by this, but I bet you wouldn't break any code by doing this. I've never seen people write code like `if a or b and c`...

**Comment by Frotty** [comment]
>  I've never seen people write code like if a or b and c...

Then you haven't seen much code

**Comment by Cokemonkey11** [comment]
> Then you haven't seen much code

I suppose everything is relative, but I've probably read some hundreds of thousands of LoC.

More interestingly, I've seen a number of style guides that recommend the extra parentheses.

Even more interestingly though is that breaking existing wurst code by fixing this can only damage code that is strictly incorrect (I think).

**Comment by peq** [comment]
I write code like this quite often. However, the Jass parser is mostly used for common.j, blizzard.j, and war3map.j. I doubt that these files will use problematic cases. So in the end it would not matter, if I change the Jass parser.

The Wurst parser will definitely stay as it is, using the standard preferences which work with every other language, that I know of.

For the Jurst parser I am not so sure... Maybe there should be a style-warning.

**Comment by Cokemonkey11** [comment]
we can just grep through blizzard.j (common.j won't contain that): `^.* or .* and .*$`

Two important things from that, I suppose:

* The output war3map.j has to be correct. The code supplied in the first example is unambiguous in either case because parentheses are used, but it is broke in the compiled version.
* If the wurst/jurst order of precedence different from that of JASS, the documentation should have a section about operator precedence.

**Comment by lep** [comment]
> Really? So what is correct? Both have the same precedence?

> In JASS, it seems they both have the same precedence, yes.

No. That's the point of the last link.
If `and` and `or` would have the same precedence then `false and true or true` should be parsed as `(false and true) or true` but wc3 says  that `(false and true or true)  !=  ((false and true) or true)` 

Indeed the following is true in wc3: `(false and true or true) == (false and (true or true))`

**Comment by peq** [comment]
Ok, so `or` has a stronger binding? Or do they have the same and they are grouped to the right? I hope that at least there are some consistent rules :D

I changed the precedences in the code, but I don't have access to Warcraft at the moment, so I will test this fix later.

**Comment by lep** [comment]
I assumed that they are left associative.
I think this code will prove atleast that `or` binds tighter:
`true and true or true and false`
If `and` and `or` would have the same precedence and be right associative it should get parsed as `(true and (true or (true and false)))` which evaluates to `true`.
But if `or` binds tighter it should be parsed as `(true and (true or true)) and false` or as `true and ((true or true) and false)` which both are `false`.


And in wc3 indeed `(true and true or true and false) == false`.

Ofc it might still be the case that `or` and `and` are both right associative and `or` binds tighter but someone other has to prove that...
I don't even know if associativity matterns with short-circuit operators...
