### ISSUE TITLE
STL handles/Unit is missing AddUnitToStock and RemoveUnitFromStock equivalents

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#453]
I'm happy to add this.

**Comment by Frotty** [comment]
No need to make a ticket for every native that is missing. There are many not done.
The stdlib isn't complete, and I know that, because I mostly did, what I needed. Feel free to just make PR, as such a change should only take you minutes with the github inline editor.

**Comment by Cokemonkey11** [comment]
Added in 7020cfd
