### ISSUE TITLE
How to deal with ForGroupCallback.callback on invalid object Error

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#456]
For example:

![forgroup-bug](https://cloud.githubusercontent.com/assets/1418966/16615942/e7294346-4371-11e6-92c9-1566e63a0de5.png)

And here is every instance of ClosureForGroups used in my map:

		guard = null // Global variable.
		forUnitsInRange(vec2(u.getX(), u.getY()), RADIUS, (unit iter) -> begin
			if iter.isAlive() and isGuardDevil(iter) and iter.hasAbility(ID_ABILITY_UNBREAKABLE)
				guard = iter
			end
		end)

and

			hasUnit = false // Global variable.
			forUnitsInRange(vec2(leviathans[pId].getX(), leviathans[pId].getY()), RADIUS, (unit iter) -> begin
				if iter.isAlive() and IsUnitEnemy(iter, owner)
					hasUnit = true
				end
			end)

and

			forUnitsInRange(vec2(tU.getX(), tU.getY()), RADIUS, (unit iter) -> begin
				if iter.isAlive() and IsUnitEnemy(iter, p)
					iter..issueTargetOrder("attack", tU)
					    ..addAbility(DAMAGE_REDUCTION_ID)

					addTaunt(iter, tU, DURATION)
				end
			end)

and

		willSacrifice = false // Global variable.
		forUnitsInRange(vec2(u.getX(), u.getY()), RADIUS, (unit iter) -> begin
			if iter.isAlive() and iter.getTypeId() == ID_THALL_BOX and iter.getOwner() == u.getOwner() and iter.hasAbility(ID_ABILITY_SACRIFICE)
				willSacrifice = true
			end
		end)

and

		splendorCheck = false // Global variable.
		forUnitsInRange(vec2(u.getX(), u.getY()), RADIUS, (unit iter) -> begin
			if iter.isAlive() and iter.getTypeId() == ID_THALL_BOX and iter.getOwner() == u.getOwner() and iter.hasAbility(ID_ABILITY_SPLENDOR)
				splendorCheck = true
			end
		end)

		return splendorCheck
	end

**Comment by peq** [comment]
I think the library is broken. The closures are never destroyed. So you might get this error, after 8191 instances of the closure have been created.

**Comment by Cokemonkey11** [comment]
Looks like `ClosureForGroups` line 8 is where the closure could be destroyed. I think @Frotty should look at this as I'm not sure how to fix.

**Comment by Frotty** [comment]
peq himself wrote this thing though
https://github.com/peq/WurstScript/commits/master/Wurstpack/wurstscript/lib/small%20helpers/ClosureForGroups.wurst
