### ISSUE TITLE
predicate examples in manual have incorrect function signature

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#467]
Here at http://peq.github.io/WurstScript/manual.html#lambda-expressions-and-closures

We have the example:

```
// a simple implementation
class IsEven implements Predicate<int>
    function isTrueFor(int x)
        return x mod 2 == 0
```

But `isTrueFor` cannot return a bool as its signature has no return type.

The interface declaration is also missing the return type:

```
// the functional interface:
interface Predicate<T>
    function isTrueFor(T t)
```

**Comment by peq** [comment]
I should make a script to compile the examples in the manual :D
