### ISSUE TITLE
shit gets borked if you extend generic types

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#478]
More details tomorrow, but the following:

http://peeeq.de/code.php?id=28309

Does not work. Line 20: `if not has(key)` breaks during compile time:

```
Error in File Hashtable.wurst line 50: null

return LoadInteger( this, parentKey, childKey )
```

Best guess is that in the context of the extended type, the parent doesn't have a pointer/reference, so it's calling `LoadInteger(null, parentKey, childKey)` instead.

Will look at this more tomorrow.

It's worth noting that changing this to `if not super.has(key)` is still broken.

**Comment by Cokemonkey11** [comment]
I tried making a version without subclassing using `fakeSuper`, but this errors during compile in the same way as before:

http://peeeq.de/code.php?id=28310

@Frotty it seem we may have been wrong about subclassing generics being the issue. It's certainly possible that my code is just wrong.

**Comment by peq** [comment]
So does the error happen when you run the tests? I can think of two possible problems in that case:

1. The hashmap functions do not work correctly in the interpreter.
2. The toIndex fromIndex functions for `int` are not found. Maybe try to write the tests with normal classes instead of using integers.

**Comment by Cokemonkey11** [comment]
A `nullPointerException` happens if you run the test as well, but with more information since there are `print` calls:

```
Testing function checkCanIterate (wurst/data structures/LinkedHashMap.wurst, line 111)	... putting
adding
hello world
putting
Error: java.lang.NullPointerException
```

If we refer to the code where "putting" and "adding" are being printed:

```
    /** Saves the given value under the given key. */
    function put(K key, V value)
        print("putting")
        if not has(key)
            print("adding")
            keys.add(key)

        fakeSuper.put(key, value)
```

It becomes especially surprising that this fails at compile time, because only when it gets to `if not has(6)` it fails. When it does `if not has(5)` it works.

Regarding 1: Wursst World Editor also fails to compile. Does map compile in the editor try to run tests? If so, this might be the issue.

Regarding 2: Other tests (including ones I added in `HashMap<>` work so I don't *think* this is problem.

For example this works:

```
@test function putTwice()
	let map = new HashMap<int, int>()

	map.put(3, 4)
	map.put(4, 5)


@test function putAndCheck()
	let map = new HashMap<int, int>()

	map.put(3, 4)
	map.has(3).assertTrue()

@test function canHaveMultipleMaps()
	let map  = new HashMap<int, int>()
	let map2 = new HashMap<int, int>()

	map. put(3, 4)
	map2.put(5, 6)

	map. get(3).assertEquals(4)
	map2.get(5).assertEquals(6)
	
	// destroy map
	// destroy map2
```

Also on a related note: `destroy HasMap<>` does not work in Wurstunit.

**Comment by Cokemonkey11** [comment]
Here is a version that uses a class instead of int. It fails in the same way at the same place at the same time:

```
class TestClass
	int val

	construct(int val)
		this.val = val


    function toString() returns string
        return "[Test Class] " + val.toString()


@test function checkCanIterate()
    let map = new LinkedHashMap<TestClass, TestClass>()
	let tc1 = new TestClass(1)
	let tc2 = new TestClass(2)
	let tc3 = new TestClass(3)
	let tc4 = new TestClass(4)

    map.put(tc1, tc2)
    print("hello world")
    map.put(tc3, tc4)
    print("hello world")

    var sum = 0

    print(".")
    let iter = map.iterator()
    print(".")
    while iter.hasNext()
        print(".")
        let entry = iter.next()
        print(".")

        sum += entry.value.val
        print(".")
    print(".")
    iter.close()
    print(".")

    sum.assertEquals(15)
    // destroy map
```

```
Testing function checkCanIterate (wurst/data structures/LinkedHashMap.wurst, line 122)	... putting
adding
hello world
putting
Error: java.lang.NullPointerException
```

**Comment by Cokemonkey11** [comment]
If I add the following: `print((fakeSuper castTo int).toString())` just before the `if not hasKey...` line, I can see that the HashMap referenced by fakeSuper has not magically changed values:

```
Testing function checkCanIterate (wurst/data structures/LinkedHashMap.wurst, line 123)	... putting
51
adding
hello world
putting
51
Error: java.lang.NullPointerException
```

**Comment by Cokemonkey11** [comment]
As mentioned in the other ticket, this was indeed a code error in the end.
