### ISSUE TITLE
Modelmanager was locked for build

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#484]
I have this problem:

https://github.com/peq/WurstScript/blob/master/EclipseWurstPlugin/src/de/peeeq/eclipsewurstplugin/builder/ModelManagerImpl.java#L114

Related: https://github.com/peq/WurstScript/issues/400

I can't execute "1 + 1" in wurst console in eclipse.

**Comment by peq** [comment]
That's the reason vscode works locking. Just wait until testing and repl
are implemented for vscode.

**Comment by Cokemonkey11** [comment]
@peq vscode and eclipse were working side by side for a few days and then it just broke.

I tried recompiling wurst but no luck.

**Comment by Cokemonkey11** [comment]
is `tests` still a long way off in the vscode client?

**Comment by Cokemonkey11** [comment]
Turns out I can't compile in game either.

![image](https://cloud.githubusercontent.com/assets/1418966/17483872/9f033c5c-5d7f-11e6-90b5-73584d428959.png)

**Comment by peq** [comment]
Interesting. That might be related to the bug with generics you
mentioned in the chat yesterday (something with Entry<K,V> cannot be
assigned to Entry<K,V>). Can you post the code for that?

Or post all the code :>

It is something with Generics according to the Stacktrace.

**Comment by peq** [comment]
Implementing tests would not be much work, but there is no standard way to
integrate tests into vscode yet. So I am not sure about the UI yet.

So I could do one of the following:

1. Show test results directly in the source code.
2. Open up a Java GUI window with the test results
3. Show test results in a console inside vscode

Regarding test support I am planning to add commands for:

- run all tests in project
- run tests in current package
- run test under cursor

(This should probably go into another ticket)



2016-08-08 16:35 GMT+02:00 Cokemonkey11 <notifications@github.com>:

**Comment by Cokemonkey11** [comment]
Here is the code which is most likely offending:

http://peeeq.de/code.php?id=28333

I commented out the part I thought could be the problem (predicates) because I had a problem with multi-type predicates in the past. Still no luck compiling.

Regarding vscode tests: I will open a new ticket.

**Comment by Cokemonkey11** [comment]
Fixed in 67bbd93e0f88940ad1508b8c19b06a8f706da73c
