### ISSUE TITLE
Can't launch map from vscode

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#485]
Steps taken:

`cntrl+shift+p`, `wurst map`, `Run a wurst map`

result:

![image](https://cloud.githubusercontent.com/assets/1418966/17484030/2bf32500-5d80-11e6-838d-c6ef4953d29c.png)

**Comment by Cokemonkey11** [comment]
@peq I can't remember if you already told me how to fix this?

**Comment by peq** [comment]
The last time you told me it worked after a restart. I don't know why it does not find the command.

**Comment by Cokemonkey11** [comment]
The tests worked after a restart but map launch still does not.

Would it be helpful to provide you with the logs, or does this error have no debug info?

**Comment by peq** [comment]
Logs would not show anything useful here. The command is registered before the test commands, so it should definitely be there. If you have some time, you could try to debug the vscode plugin by starting it from the sources and setting some breakpoints to see what happens.

**Comment by Cokemonkey11** [comment]
So, just to clarify, I should build the vscode plugin from source? Where can I find build instructions? The readme is for vscode marketplace.

**Comment by peq** [comment]
Yes, I have added a short description on how to run it: https://github.com/peq/wurst4vscode#developer-information (not sure if that's enough to get started)

**Comment by Cokemonkey11** [comment]
Okay, I have left home in a hurry today so I'm not sure I'll ever get to this anymore.

**Comment by Cokemonkey11** [comment]
@peq, coming back to this to try and close it off. I've got the latest versions of everything again.

Now the "run wurst map" option works, and allows me to select a mapfile.

Once I select it though, I get this:

`There was a Wurst bug, while compiling the map: c:\Users\Blake\workspace\the-gorge\(10)TheGorge0.9.1.w3x (Access is denied)`

**Comment by Frotty** [comment]
monkey had vscode run working last time we spoke. Should be fixed.
