### ISSUE TITLE
regression: underscore is no longer valid at the start of a function name

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#487]
![image](https://cloud.githubusercontent.com/assets/1418966/17498327/9b912158-5dbe-11e6-9efc-69c581de534b.png)

this used to work just fine

**Comment by Cokemonkey11** [comment]
@peq, fixed in 51b8db1 ?

**Comment by peq** [comment]
No, that was just too suppress some warnings. This has to be fixed in the jass printer. You can just enable the optimizer, to give all functions new names until it's fixed.

**Comment by Cokemonkey11** [comment]
Okay, guessing this wants to be scheduled as low-priority bug-fix
