### ISSUE TITLE
LinkedList iterator .remove() doesn't decrease size

### ISSUE THREAD

**Issue by BlueSaint** [peq/WurstScript#488]
I have very recently started using Wurstscript, so this might be intended behavior as well. I wrote a little example of what I mean by this issue:
```
import LinkedList

@test function testFunc()
	LinkedList<int> list = new LinkedList<int>
	..add(1)
	..add(2)
	..add(3)
	..add(4)
	let iterator = list.iterator()
	while iterator.hasNext()
		iterator.next()
		iterator.remove()
	iterator.close()
	print(list.getSize().toString())
	destroy list
```
The print should give you 0, but it gives me 4 instead.

**Comment by Cokemonkey11** [comment]
Hi @BlueSaint ,

This was fixed 5 days ago in ee9ac02dcf93dc1aa2023399325ffe9261f415e1 .

Are you able to update your wurst std library? If you don't know how, can you please let us know how you acquired/installed wurst?

**Comment by BlueSaint** [comment]
It was fixed 5 days ago but I downloaded Wurst yesterday...
I used WurstUpdater.jar and it gave me Wurstpack - folder

**Comment by Cokemonkey11** [comment]
@BlueSaint okay, great, sounds like you are compiling wurst. Currently, the Wurstpack folder contains a copy of the standard library, but the standard library was just recently (around 6 days ago) split into a separate repository:

https://github.com/peq/wurstStdlib

So you'll want to do the following:

* clone the new standard library folder into a folder in your workspace
* change your map's `wurst.dependencies` file to point to this new copy of the stl.

**Comment by Frotty** [comment]
Hi BlueSaint. And no coke, he is not compiling, he just used the updater.
See https://github.com/peq/wurstStdlib
