### ISSUE TITLE
Move log location from temp folder to somewhere else

### ISSUE THREAD

**Issue by peq** [peq/WurstScript#495]
Or store them in a different folder inside the temp folder.

**Comment by Frotty** [comment]
Either the temp folder should be relative to the project (.wurst folder could work, which is cleaned) to avoid problems when the project is on a different drive than the temp folder (https://github.com/peq/wurst4vscode/issues/13)

Or the relativize call must be replaced with something that handles multiple roots, examples here https://stackoverflow.com/questions/204784/how-to-construct-a-relative-path-in-java-from-two-absolute-paths-or-urls

**Comment by Frotty** [comment]
moved to %t/wurst/wurst.log
