### ISSUE TITLE
Jass generated by JassHelper invalid for wurst.

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#498]
This library http://www.hiveworkshop.com/threads/sync-game-cache.279148/

Everywhere ``this`` is used
````
//Generated allocator of SyncData
function s__SyncData__allocate takes nothing returns integer
 local integer this=si__SyncData_F
    if (this!=0) then
````
-> ``Cannot use 'this' in static methods.``

![image](https://cloud.githubusercontent.com/assets/1486037/21738197/b5c598c6-d481-11e6-9782-558980ab4af7.png)

TriggerRegisterVariableEvent is not allowed, maybe add a workaround or something

**Comment by peq** [comment]
Using 'this' as variable name in Jass should work now.

The workaround for TriggerRegisterVariableEvent is to not use it and call the trigger manually when changing the variable.
The only valid use case for this function is supporting GUI stuff.
