### ISSUE TITLE
Destroy Triggers created by managed initialization

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#502]
The check if a package was inited is nice, but please destroy all these triggers.
![image](https://cloud.githubusercontent.com/assets/1486037/21913381/5d9a2d10-d92c-11e6-86bd-88aa4c10610a.png)

and i think this might cause the triggersyncstuff to fail. Might be wrong tho

**Comment by peq** [comment]
It's just a finite number of triggers, what's the problem? :D

**Comment by Frotty** [comment]
Yea it's probably not causing any side effects apart from the leaks. Fix seems to work, thanks.
