### ISSUE TITLE
Stacktraces crash wc3 when getting too big

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#514]
Maybe use BigString or add a simple check.

**Comment by peq** [comment]
Maybe we can change it to use one global array for the stack trace. That would be more efficient, but there are some cases where it might give different stack-traces.

**Comment by Frotty** [comment]
Or truncate with "...".
This is still and issue since I can't run EBR with stacktraces + inliner.

**Comment by peq** [comment]
I am working on an alternative stacktrace implementation on branch `new-stacktraces`. It is not tested yet, but if you want you can try it and report bugs about it.

**Comment by peq** [comment]
merged the fix (tested with small example)
