### ISSUE TITLE
Wurst World Editor launches a RoC worldedit shell after patching to 1.28

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#515]
This suggests it could be related to CD-key locations - https://www.hiveworkshop.com/threads/feedback-compiled-list-of-1-28-issues.293010/

JNGP has the same issue.

**Comment by Frotty** [comment]
see https://www.hiveworkshop.com/threads/self-fix-for-jngp-on-patch-1-28.293026/
