### ISSUE TITLE
Eclipse doesnt highlight use of "this" with static array but it cause Eliminate Tuples Error in Editor (of course)

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#519]
![screenshot_15](https://user-images.githubusercontent.com/29229748/26871558-49522016-4b7c-11e7-8068-3ac2b8a61565.jpg)
![screenshot_12](https://user-images.githubusercontent.com/29229748/26870587-249f2a28-4b79-11e7-9324-c6d3cd2328af.jpg)
It highlight regular static members with "this" as error. But ignores "this" with static arrays:
![screenshot_14](https://user-images.githubusercontent.com/29229748/26871447-d16d52c8-4b7b-11e7-9a1a-b2cee8bb122b.jpg)
The problem is that Eclipse **does not highlight** this error. So I searched for it for a long time to fix it

**Comment by Frotty** [comment]
Hi, thanks for the report, there was indeed an error missing for array access that was in place for non-array access. I pushed a fix that displays an error now so it doesn't come to the unimplemented tuple stuff.
