### ISSUE TITLE
TempMerger cannot be run multiple times on the same program

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#520]

**Comment by peq** [comment]
I tried running it twice on the unit tests and on EBR -- No problems. Can you give me some code where it fails?

**Comment by Frotty** [comment]
i just run all operations in "local opts" 2 times, and it excepted at tempmerger.
I can re-check later.

**Comment by Frotty** [comment]
okay tempmerger requires a flat program. Flattening before solves it.
