### ISSUE TITLE
Autocomplete still prefers BJ functions

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#524]
IIRC you added a penalty for those. Not sure why they still pop up first.
Others only appear upon re-query.

![](https://i.imgur.com/bDvvWok.png)

**Comment by peq** [comment]
there are only BJ functions in your example. So the problem seems to be that some functions are not picked up.

Maybe there are too many functions in the first request, in which case not all completions are computed for performance reasons.

**Comment by Frotty** [comment]
well at first there are more, when I havn't timed so much. Then they get less but only BJs show up instead of natives,

**Comment by peq** [comment]
This seems to be fixed with the change to the official language server library.
