### ISSUE TITLE
Error when try to save map in WurstWE

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#525]
![screenshot_2](https://user-images.githubusercontent.com/29229748/27243417-752289ea-52ea-11e7-999e-c4447cb401a4.png)
What does it mean?
This happens even when the wurst folder is empty.
![screenshot_3](https://user-images.githubusercontent.com/29229748/27243478-c184ac82-52ea-11e7-94fc-4996b25de76a.png)
Only Enable WurstScript is selected.
Is it due to changes in the latest 324 build? (remove jmpq2 from wurstpack)

**Comment by vitalexbel** [comment]
updated to 1.28. check it later

**Comment by Frotty** [comment]
You should rather update your wurstpack, since zopfli shouldn't be used with recent versions.
