### ISSUE TITLE
1.28.3 support

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#529]
The new patch fucked up everything again. Yay.

- [x] ~~RunMap needs to reference the new .exe names correctly (maybe add some auto-detect or browse feature so it stays compatible)~~
- [x] Wurstpack seems broken now. Something inside grimoire throws an exception, doesn't seem to be easily fixable (WEX? Own solution?)

report any other here.

**Comment by Frotty** [comment]
no longer a blocker since running from vscode works

**Comment by Cokemonkey11** [comment]
Regarding WEX: I've been chatting with MindWorX via direct message on the Hive Workshop discord channel. This seems to be a good way to contact him.

We're aiming to support wurst today/tomorrow, and he also has plans to eventually get some sort of WEX repository to make it a bit easier to update wurst dependencies.

**Comment by vitalexbel** [comment]
WurstWE cant find game .exe file in 1.28.4 last update too.
VScode give "This socket has been ended by the other party" warning when I try to start map.

**Comment by Frotty** [comment]
wurstwe is in the process of being fixed. vscode already works, so use that in the meantime.

**Comment by Frotty** [comment]
Wurstpack now works again by creating a compatability copy of the existing installation. see 86bc99fa6f0bc5e62b5c5d7dd0f48d21f5ea047d
Please test and report.
