### ISSUE TITLE
Deploy tasks deploy too many .jars

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#530]
E.g. make_for_wurstpack also copies libs like jzlib and minlog, which are included inside the jmpq3 jar.
Copying everything from installDist might not be the best idea.

**Comment by peq** [comment]
Hm, the question is why the Jmpq jar contains its dependencies. Usually that is not done afaik.

**Comment by peq** [comment]
Closing this, because I think it should be fixed in Jmpq.

**Comment by Frotty** [comment]
It does it so the .jar can be downloaded from github releases without requiring addtional .jars, but you are right, it should be a different task, which I have done now.
