### ISSUE TITLE
Running wurstscript.exe does nothing

### ISSUE THREAD

**Issue by TinkerWorX** [peq/WurstScript#535]
I'm in the process of helping @Cokemonkey11 with adding WurstScript to WEX(#529), and I've hit a problem. When I run wurstscript.exe nothing happens, here are the things I've tried

- Running wurstscript.exe in cmd/powershell
- Running wurstscript.exe -gui in cmd/powershell
- Running wurstscript.exe \<absolute path to common.j\> \<absolute path to blizzard.j\> \<absolute path to map\>

In all cases, nothing happens. The process starts and immediately closes with no output and with an exitcode of 0.

I've tried running wurstscript_b.exe to see if it behaved differently, and here I got an error about being unable to connect to the server. This leads me to believe I might be missing a dependency which is only used in wurstscript.exe.

I'm running Windows 10 with the most recent updates and I have JRE x86 and JRE x64 installed. I have not modified any environment variables, just installed both JREs and then tried using wurstscript.exe.

**Comment by Cokemonkey11** [comment]
Also he has no debug logs in `AppData\Local\Temp\wurst\`.

One further diag: I suspect he's using the x86 JRE since wurstscript was previously complaining that he was missing java, so that's a fresh install and cleared that problem.

**Comment by Cokemonkey11** [comment]
@Frotty can you take a look when you wake up

**Comment by Frotty** [comment]
Works perfectly as expected.
![](https://i.imgur.com/gt69mKn.png)

make sure you have Java **8** installed and set JAVA_HOME correctly.

**Comment by TinkerWorX** [comment]
I have Java 8 and running wurstscript.exe --about does nothing. Do I have to set JAVA_HOME manually?

**Comment by TinkerWorX** [comment]
The jars were missing, resulting in a silent error. An improvement would be to detect this.

**Comment by Frotty** [comment]
While I agree that an error could help, unless you want to build on your own, you would never download the source repo, so the .jars would always be there for a normal user that follows instructions.

**Comment by Cokemonkey11** [comment]
I think your answer leaves opportunity for discussion, but better more definitive one is probably just "we should delete wurstscript.exe since wurstpack is not supported anymore"

**Comment by Frotty** [comment]
nope.

**Comment by Cokemonkey11** [comment]
How did you achieve that?

**Comment by Frotty** [comment]
by not giving up after first attempt
