### ISSUE TITLE
wurstscript.exe sourcecode - missing?

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#536]

**Comment by peq** [comment]
There is no sourcecode for `wurstscript.exe`  because it was generated by some java-exe-wrapper generator. The `wurstscript_b.exe` had some sourcecode, maybe we accidentally removed that in the recent cleanup process.

**Comment by peq** [comment]
I reverted the code for `wurstscript_b.exe`: https://github.com/peq/WurstScript/tree/master/WurstStarter

**Comment by Cokemonkey11** [comment]
@peq okay, is there any value in beefing up `wurstscript.exe`, or possibly the jar is what needs better debug info?

Frotty says wurstpack is still used, so I think wurstscript.exe is used too.

**Comment by peq** [comment]
Not sure I understand what you mean here. 

The `wurstscript.exe` is really just a wrapper which tries to locate the Java executable and runs the `wurstscript.jar`.  It is only needed, because Grimoire somehow could not run Java without such a wrapper. 

If you want to improve the wrapper somehow, you're welcome to do so, but I always avoided changing it because that might also break the setup for someone.

**Comment by Frotty** [comment]
yes, but if there is no .jar, it fails silently.
Ideally it should show an error or something.

**Comment by Cokemonkey11** [comment]
Okay, we agreed that it might be worth to:

* choose version of java, probably checking JAVA_HOME, and then checking for java in PATH, before raising exception
* pass whatever arguments given to it to java as a subprocess, by running `{java_path} -jar wurstscript.jar {arguments}
* possibly also adding java run arguments like heap size

Question: if there's no .jar it should fail loudly. With `java -jar` that looks like this:

```
C:\Users\Blake>java -jar braap.jar
Error: Unable to access jarfile braap.jar
```

Shall we catch this, or shall we make `wurstscript.exe` something more than just a dumb wrapper? i.e. check that filesystem path exists?

* Something else?

@Frotty @peq

**Comment by Frotty** [comment]
imo the exe should check for existence of the jar before running the command. But I suppose it doesn't matter as long as there appears an error.

**Comment by Cokemonkey11** [comment]
Fine. Any particular java heap arguments to pass? hardcoded or in config file?
