### ISSUE TITLE
Adding print(int) and print(real) functions

### ISSUE THREAD

**Issue by IgorSamurovic** [peq/WurstScript#546]
This is a very minor thing (and I could implement this for myself) but considering that the end user uses print exclusively for debugging, wouldn't it make sense to add overloaded functions that take int and real as well?

When you just want to quickly observe some value, writing .toString() is kind of annoying considering that the language can do better.

Obviously, languages like Java call .toString() by default if available (and implicit calls like this would be a bad feature for wurst, I think), but I think adding overloaded functions for at least int and real would be good, without obvious downsides.

The alternative solution would be making print (and print alone, not wurst in general) call .toString() no matter the input, but I don't think that's a good idea.

**Comment by Frotty** [comment]
Ticket belongs to stdlib repo I believe (https://github.com/Frotty/wurstStdlib2), maybe move it there.
I don't think anything speaks against some overloaded printing functions, as long as it doesnt get too crazy. Feel free to make a pull request for the Printing package.

**Comment by Frotty** [comment]
see https://github.com/Frotty/wurstStdlib2/pull/4
